# Generated by Django 3.2 on 2022-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_feautured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feautured',
            options={'verbose_name': 'Featured', 'verbose_name_plural': 'Featured'},
        ),
        migrations.AlterField(
            model_name='feautured',
            name='products',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='products.Product'),
        ),
    ]
